on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 15 minutes

jobs:
  ping_url:
    runs-on: ubuntu-latest
    name: Ping URL
    steps:
      - name: Ping the URL
        uses: soul-wish/ping-url-javascript-action@v1.5
        with:
          url: "https://last-fmstatus.onrender.com/"
